apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: sampleapp
        image: docker.io/lazyken/sampleapp:v1
        resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
        resources:
          limits:
            cpu: '700m'
            memory: '300Mi'
          requests:
            cpu: '100m'
            memory: '100Mi'
        env:
        - name: USER_NAME
          value: 'LAZYken'
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 5000 # Port app is running
---
apiVersion: v1 
kind: Service 
metadata:
  name: hello
spec: 
  type: NodePort 
  selector: 
    app: hello 
  ports: 
    - targetPort: 5000    # Port on pod (The port the application container is actually listening on inside the Pod.)
      port: 80            # Port for service (For internal access)
      nodePort: 32593     # Port for node (For external access)