apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: sampleapp
        image: docker.io/lazyken/sampleapp:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: USER_NAME
          value: 'LAZYken'
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: hello
spec: 
  type: NodePort 
  selector: 
    app: hello 
  ports: 
    - targetPort: 5000    # Port on pod
      port: 80            # Port for service
      nodePort: 32593     # Port for node