apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: docker.io/lazyken/measure-app:v1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: '192.168.17.162'
            - name: DB_USER
              value: 'thai'
            - name: DB_PASSWORD
              value: 'PQThai29112003'