apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: sampleapp
        image: docker.io/lazyken/measure-app:v1
        resources:
          limits:
            cpu: '700m'
            memory: '300Mi'
          requests:
            cpu: '100m'
            memory: '100Mi'
        env:
        - name: DB_HOST
          value: '192.168.17.162'
        - name: DB_USER
          value: 'thai'
        - name: DB_PASSWORD
          value: 'PQThai29112003'
        ports:
        - containerPort: 5000 # Port app is running
---
apiVersion: v1 
kind: Service 
metadata:
  name: hello
spec: 
  type: NodePort 
  selector: 
    app: hello 
  ports: 
    - targetPort: 5000    # Port on pod (The port the application container is actually listening on inside the Pod.)
      port: 80            # Port for service (For internal access)
      nodePort: 32593     # Port for node (For external access)