apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: docker.io/lazyken/sampleapp:v1
          ports:
            - containerPort: 80
          env:
            - name: USER_NAME
              value: 'LAZYken'
            - nodeName: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            